/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.saydos.markazcompta.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ARTICLE
	VIEW_ARTICLE("VIEW_ARTICLE"),	
	CREATE_ARTICLE("CREATE_ARTICLE"),
	UPDATE_ARTICLE("UPDATE_ARTICLE"),
	DELETE_ARTICLE("DELETE_ARTICLE"),
	// CAISSE
	VIEW_CAISSE("VIEW_CAISSE"),	
	CREATE_CAISSE("CREATE_CAISSE"),
	UPDATE_CAISSE("UPDATE_CAISSE"),
	DELETE_CAISSE("DELETE_CAISSE"),
	// CHARGE_FIXE
	VIEW_CHARGE_FIXE("VIEW_CHARGE_FIXE"),	
	CREATE_CHARGE_FIXE("CREATE_CHARGE_FIXE"),
	UPDATE_CHARGE_FIXE("UPDATE_CHARGE_FIXE"),
	DELETE_CHARGE_FIXE("DELETE_CHARGE_FIXE"),
	// DEMANDE
	VIEW_DEMANDE("VIEW_DEMANDE"),	
	CREATE_DEMANDE("CREATE_DEMANDE"),
	UPDATE_DEMANDE("UPDATE_DEMANDE"),
	DELETE_DEMANDE("DELETE_DEMANDE"),
	// DEMANDE_HISTORIQUE
	VIEW_DEMANDE_HISTORIQUE("VIEW_DEMANDE_HISTORIQUE"),	
	CREATE_DEMANDE_HISTORIQUE("CREATE_DEMANDE_HISTORIQUE"),
	UPDATE_DEMANDE_HISTORIQUE("UPDATE_DEMANDE_HISTORIQUE"),
	DELETE_DEMANDE_HISTORIQUE("DELETE_DEMANDE_HISTORIQUE"),
	// DEPENSE
	VIEW_DEPENSE("VIEW_DEPENSE"),	
	CREATE_DEPENSE("CREATE_DEPENSE"),
	UPDATE_DEPENSE("UPDATE_DEPENSE"),
	DELETE_DEPENSE("DELETE_DEPENSE"),
	// DIRECTION
	VIEW_DIRECTION("VIEW_DIRECTION"),	
	CREATE_DIRECTION("CREATE_DIRECTION"),
	UPDATE_DIRECTION("UPDATE_DIRECTION"),
	DELETE_DIRECTION("DELETE_DIRECTION"),
	// MARKAZ
	VIEW_MARKAZ("VIEW_MARKAZ"),	
	CREATE_MARKAZ("CREATE_MARKAZ"),
	UPDATE_MARKAZ("UPDATE_MARKAZ"),
	DELETE_MARKAZ("DELETE_MARKAZ"),
	// RECETTE
	VIEW_RECETTE("VIEW_RECETTE"),	
	CREATE_RECETTE("CREATE_RECETTE"),
	UPDATE_RECETTE("UPDATE_RECETTE"),
	DELETE_RECETTE("DELETE_RECETTE"),
	// ROLE
	VIEW_ROLE("VIEW_ROLE"),	
	CREATE_ROLE("CREATE_ROLE"),
	UPDATE_ROLE("UPDATE_ROLE"),
	DELETE_ROLE("DELETE_ROLE"),
	// STOCK
	VIEW_STOCK("VIEW_STOCK"),	
	CREATE_STOCK("CREATE_STOCK"),
	UPDATE_STOCK("UPDATE_STOCK"),
	DELETE_STOCK("DELETE_STOCK"),
	// STOCK_HISTORIQUE
	VIEW_STOCK_HISTORIQUE("VIEW_STOCK_HISTORIQUE"),	
	CREATE_STOCK_HISTORIQUE("CREATE_STOCK_HISTORIQUE"),
	UPDATE_STOCK_HISTORIQUE("UPDATE_STOCK_HISTORIQUE"),
	DELETE_STOCK_HISTORIQUE("DELETE_STOCK_HISTORIQUE"),
	// UTILISATEUR
	VIEW_UTILISATEUR("VIEW_UTILISATEUR"),	
	CREATE_UTILISATEUR("CREATE_UTILISATEUR"),
	UPDATE_UTILISATEUR("UPDATE_UTILISATEUR"),
	DELETE_UTILISATEUR("DELETE_UTILISATEUR"),
	// UTILISATEUR_DIRECTION
	VIEW_UTILISATEUR_DIRECTION("VIEW_UTILISATEUR_DIRECTION"),	
	CREATE_UTILISATEUR_DIRECTION("CREATE_UTILISATEUR_DIRECTION"),
	UPDATE_UTILISATEUR_DIRECTION("UPDATE_UTILISATEUR_DIRECTION"),
	DELETE_UTILISATEUR_DIRECTION("DELETE_UTILISATEUR_DIRECTION"),
	// UTILISATEUR_ROLE
	VIEW_UTILISATEUR_ROLE("VIEW_UTILISATEUR_ROLE"),	
	CREATE_UTILISATEUR_ROLE("CREATE_UTILISATEUR_ROLE"),
	UPDATE_UTILISATEUR_ROLE("UPDATE_UTILISATEUR_ROLE"),
	DELETE_UTILISATEUR_ROLE("DELETE_UTILISATEUR_ROLE");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
